// import './styles/globals.scss';
// import localFont from 'next/font/local';
// import LeftNavBar from './components/LeftNavBar';
// import TopBar from './components/TopBar';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//         <TopBar />
//         <LeftNavBar />
//       </body>
//     </html>
//   );
// }

import './styles/globals.scss';
import localFont from 'next/font/local';
import { cookies } from 'next/headers';
import LeftNavBar from './components/LeftNavBar';
import TopBar from './components/TopBar';
import { getValidSessionToken } from './database/sessions';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const sessionTokenCookie = cookieStore.get('sessionToken');
  const sessionToken =
    sessionTokenCookie &&
    (await getValidSessionToken(sessionTokenCookie.value));

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        {/* Pass sessionToken as a prop */}
        <TopBar sessionToken={!!sessionToken} />
        <LeftNavBar />
      </body>
    </html>
  );
}
